import { Project } from '../types';

// Note: Projects are ordered from most recent to oldest (2025 first)
export const PROJECTS: Project[] = [
    // ==================== 2025 PROJECTS (SPOTLIGHT) ====================
    {
        id: 'changement-detat',
        title: "Changement d'état",
        subtitle: 'Installation immersive',
        category: 'Installation / Textile',
        year: '2025',
        location: 'Paris',
        imageUrl: 'https://images.unsplash.com/photo-1578301978018-3005759f48f7?auto=format&fit=crop&q=80&w=1200',
        galleryImages: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800'],
        description: 'Installation immersive de 3 × 3 mètres.',
        technicalData: "Photographie analogique 35 mm, collage, textiles teints à l'oignon et broderie à la main.",
    },
    {
        id: 'la-tisseuse',
        title: 'La Tisseuse',
        subtitle: 'Installation collective',
        category: 'Installation / Textile',
        year: '2025',
        location: 'Paris',
        imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=1200',
        galleryImages: [
            'https://images.unsplash.com/photo-1606722590583-6951b5ea92ad?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1594631661960-34bc47d23b93?auto=format&fit=crop&q=80&w=800',
        ],
        description: "Installation collective explorant la douleur féminine et l'usage du textile comme acte de résilience.",
        technicalData:
            'Fils de laine et de coton teints à la main, fils métalliques crochetés, sculpture, dentelle aux fuseaux, photographie argentique 35 mm sur mousseline de soie.',
    },
    {
        id: 'residencia-ny20',
        title: 'Résidence NY20+',
        subtitle: 'Chengdu, Sichuan, Chine',
        category: 'Residency / Installation',
        year: '2025',
        location: 'Chengdu, China',
        imageUrl: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&q=80&w=1200',
        galleryImages: ['https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&q=80&w=800'],
        description: "Résidence internationale soutenue par Nongyuan Culture, dédiée à la promotion artistique et à l'échange culturel.",
        technicalData: 'Photographie analogique 35 mm, collage, et broderie.',
    },
    // ==================== HIGH PRIORITY: AU MILIEU DE MURS FRAGILES ====================
    {
        id: 'murs-fragiles',
        title: 'Au Milieu de Murs Fragiles',
        subtitle: 'Projet en étapes',
        category: 'Installation / Public Intervention',
        year: '2021–2025',
        location: 'Paris / Public Space',
        imageUrl: 'https://images.unsplash.com/photo-1504198458649-3128b932f49e?auto=format&fit=crop&q=80&w=1200',
        galleryImages: ['https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&q=80&w=800'],
        description: 'Projet en étapes articulant mémoire, territoire et héritage.',
        technicalData: 'Tente: 130 × 210 × 107 cm. Texte brodé à la main, photographie argentique 35 mm.',
        // Special flag for multi-stage project with poem
        conceptNote: 'MULTI_STAGE_PROJECT',
    },
    // ==================== EXISTING PROJECTS ====================
    {
        id: 'volver-al-gesto',
        title: 'Volver al Gesto',
        subtitle: 'The Body as Memory',
        category: 'Conceptual / Analog',
        year: '2024',
        location: 'Buenos Aires',
        imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=1200',
        galleryImages: [
            'https://images.unsplash.com/photo-1508921234172-b68ed335b3e6?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1496449903678-68ddcb189a24?auto=format&fit=crop&q=80&w=800',
        ],
        description: 'A study on the involuntary movements of the human form when at rest. A return to the essential stillness of the flesh.',
        technicalData: 'Analog 35mm. Natural light.',
    },
    {
        id: 'diez-rollos',
        title: 'Diez Rollos 35mm',
        subtitle: 'Unedited Sequences',
        category: 'Documentary',
        year: '2023',
        location: 'Metropolitan Area',
        imageUrl: 'https://images.unsplash.com/photo-1495121553079-4c61bbbc19ef?auto=format&fit=crop&q=80&w=1200',
        galleryImages: [
            'https://images.unsplash.com/photo-1516724562728-afc824a36e84?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1452784444945-3f422708fe5e?auto=format&fit=crop&q=80&w=800',
        ],
        description: 'A chronological exploration of a city through ten consecutive rolls of film. No edits, no omissions.',
        technicalData: 'Kodak Portra 400.',
    },
    {
        id: 'paredes-endebles',
        title: 'Paredes Endebles',
        subtitle: 'Au Milieu de Murs Fragiles',
        category: 'Installation / Textile',
        year: '2024',
        location: 'Public Space',
        imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1200',
        galleryImages: [
            'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
        ],
        description: 'An investigation into the fragility of home. A tent with embroidered text, installed as a puncture in the public thoroughfare.',
        technicalData: 'Installation: 130 x 210 x 107cm.',
    },
    {
        id: 'habitar',
        title: 'Habitar los espacios',
        subtitle: 'Liquid Ethics',
        category: 'Landscape',
        year: '2018',
        location: 'Spain Coastline',
        imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?auto=format&fit=crop&q=80&w=1200',
        galleryImages: [
            'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1439405326854-015183f60bd3?auto=format&fit=crop&q=80&w=800',
        ],
        description: 'Since the oceans existed, their waters have an ethics. The waves arrive and dissolve at your feet.',
        conceptNote: 'The wind is interesting because it moves the sea.',
        technicalData: 'Analog 35mm.',
    },
    {
        id: 'certificado-ausencia',
        title: 'Certificado de ausencia',
        subtitle: 'Domestic Ghosts',
        category: 'Still Life / Portrait',
        year: '2023',
        location: 'Abandoned Structures',
        imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=1200',
        galleryImages: [
            'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&q=80&w=800',
            'https://images.unsplash.com/photo-1524061511843-fd43443e3cb2?auto=format&fit=crop&q=80&w=800',
        ],
        description: 'A certificate of presence for those who are no longer there. Objects as silent witnesses.',
        technicalData: 'Medium Format.',
    },
    {
        id: 'hibrido',
        title: 'Híbrido',
        subtitle: 'Natures of the Artificial',
        category: 'Experimental',
        year: '2022',
        location: 'Botanical / Urban',
        imageUrl: 'https://images.unsplash.com/photo-1492446845049-9c50ce313d00?auto=format&fit=crop&q=80&w=1200',
        description: 'The collision between biological growth and synthetic structures. A hybrid existence.',
        technicalData: 'Mixed Media.',
    },
    {
        id: 'torso-nomiente',
        title: 'El torso no miente',
        subtitle: 'Honest Postures',
        category: 'Portrait',
        year: '2021',
        location: 'Studio',
        imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=1200',
        description: 'Movement can be rehearsed, but the weight of the torso reveals the truth of the body.',
        technicalData: 'Black & White.',
    },
    {
        id: 'dilucidar',
        title: 'Dilucidar',
        subtitle: 'To Clarify',
        category: 'Abstract',
        year: '2020',
        location: 'Darkroom',
        imageUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=1200',
        description: 'An investigation of light as a primary tool of dissection.',
        technicalData: 'Experimental printing.',
    },
];

// Helper to get 2025 spotlight projects
export const SPOTLIGHT_PROJECTS = PROJECTS.filter((p) => p.year === '2025' || p.year === '2021–2025');
